version: "3"

services:
  one:
    build: ./bot
    restart: always
    hostname: one
    ports:
      - "3000:3000"
    volumes:
      - ./one/settings.json:/usr/src/app/settings.json
    command: bash -c "npm run dev"

  two:
    build: ./bot
    restart: always
    hostname: two
    ports:
      - "3001:3000"
    volumes:
      - ./two/settings.json:/usr/src/app/settings.json
    command: bash -c "npm run dev"

  three:
    build: ./bot
    restart: always
    hostname: three
    ports:
      - "3002:3000"
    volumes:
      - ./three/settings.json:/usr/src/app/settings.json
    command: bash -c "npm run dev"
