version: "3"

services:
  jsbot:
    image: node:14
    restart: always
    volumes:
      - bot_db:/usr/app/db
      - ./js:/usr/app
    command: bash -c "cd /usr/app && npm install && npm run dev"

volumes:
  bot_db:
